[tool.poetry]
name = "day 08"
version = "0.1.0"
description = ""
authors = ["Scott Barclay <scott.barclay@ncontracts.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
